name: Download Toolchain

inputs:
  toolchain:
    description: 'Toolchain name'
    required: true
  toolchain_url:
    description: 'Toolchain URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Toolchain
      uses: actions/cache@v4
      id: cache-toolchain-download
      with:
        path: ~/cache/${{ inputs.toolchain }}
        key: ${{ runner.os }}-${{ inputs.toolchain }}-${{ inputs.toolchain_url }}

    - name: Install Toolchain
      if: steps.cache-toolchain-download.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/cache/${{ inputs.toolchain }}
        wget --progress=dot:mega ${{ inputs.toolchain_url }} -O toolchain.tar.gz
        tar -C ~/cache/${{ inputs.toolchain }} -xaf toolchain.tar.gz
      shell: bash

    - name: Set Toolchain Path
      run: |
        echo >> $GITHUB_PATH `echo ~/cache/${{ inputs.toolchain }}/*/bin`
      shell: bash
