include ../../make.mk

INC += \
	src \


# Example source
SRC_C += $(addprefix $(EXAMPLE_PATH)/, $(wildcard src/*.c))
SRC_CXX += $(addprefix $(EXAMPLE_PATH)/, $(wildcard src/*.cc))

include ../../rules.mk
