var searchData=
[
  ['os_20abstraction_20layer_20_28osal_29',['OS Abstraction Layer (OSAL)',['../group__group__osal.html',1,'']]],
  ['ochi_5fitd_5ft',['ochi_itd_t',['../structochi__itd__t.html',1,'']]],
  ['offset',['offset',['../structehci__itd__t.html#a2df482bb0528381abc0a05905bb5826a',1,'ehci_itd_t']]],
  ['ohci',['OHCI',['../group___o_h_c_i.html',1,'']]],
  ['ohci_2ec',['ohci.c',['../ohci_8c.html',1,'']]],
  ['ohci_2eh',['ohci.h',['../ohci_8h.html',1,'']]],
  ['ohci_5fdata_5ft',['ohci_data_t',['../structohci__data__t.html',1,'']]],
  ['ohci_5fed_5ft',['ohci_ed_t',['../structohci__ed__t.html',1,'']]],
  ['ohci_5fgtd_5ft',['ohci_gtd_t',['../structohci__gtd__t.html',1,'']]],
  ['ohci_5fhcca_5ft',['ohci_hcca_t',['../structohci__hcca__t.html',1,'']]],
  ['ohci_5fregisters_5ft',['ohci_registers_t',['../structohci__registers__t.html',1,'']]],
  ['ohci_5ftd_5fitem_5ft',['ohci_td_item_t',['../structohci__td__item__t.html',1,'']]],
  ['osal_2eh',['osal.h',['../osal_8h.html',1,'']]],
  ['osal_5fcmsis_5frtx_2eh',['osal_cmsis_rtx.h',['../osal__cmsis__rtx_8h.html',1,'']]],
  ['osal_5fcommon_2eh',['osal_common.h',['../osal__common_8h.html',1,'']]],
  ['osal_5ffreertos_2eh',['osal_freeRTOS.h',['../osal__free_r_t_o_s_8h.html',1,'']]],
  ['osal_5fmutex_5ft',['osal_mutex_t',['../structosal__mutex__t.html',1,'']]],
  ['osal_5fnone_2ec',['osal_none.c',['../osal__none_8c.html',1,'']]],
  ['osal_5fnone_2eh',['osal_none.h',['../osal__none_8h.html',1,'']]],
  ['osal_5fqueue_5ft',['osal_queue_t',['../structosal__queue__t.html',1,'']]],
  ['osal_5fsemaphore_5ft',['osal_semaphore_t',['../structosal__semaphore__t.html',1,'']]],
  ['osal_5ftask_5ft',['osal_task_t',['../structosal__task__t.html',1,'']]],
  ['over_5fcurrent_5factive',['over_current_active',['../structehci__registers__t.html#ace6b84aff30f539cc19f9c8d7607b9d6',1,'ehci_registers_t']]],
  ['over_5fcurrent_5fchange',['over_current_change',['../structehci__registers__t.html#a9dcaa14f2998d9ae0a59c4e314446ced',1,'ehci_registers_t']]]
];
