MCU_VARIANT = APM32F072xB
MCU_LINKER_NAME = APM32F07xxB

JLINK_DEVICE = APM32F072RB

CFLAGS += \
  -D${MCU_VARIANT} \
  -DCFG_EXAMPLE_MSC_READONLY \
  -DCFG_EXAMPLE_MSC_DUAL_READONLY \
  -DCFG_EXAMPLE_VIDEO_READONLY
