include ../../make.mk

INC += \
	src \
	$(TOP)/hw \

# Example source
SRC_C += $(addprefix $(CURRENT_PATH)/, $(wildcard src/*.c))
SRC_CXX += $(addprefix $(CURRENT_PATH)/, $(wildcard src/*.cc))

include ../../rules.mk
