MCU_VARIANT = AT32F405RCT7
MCU_LINKER_NAME = AT32F405xC

JLINK_DEVICE = ${MCU_VARIANT}

RHPORT_SPEED = OPT_MODE_FULL_SPEED OPT_MODE_HIGH_SPEED
RHPORT_DEVICE ?= 1
RHPORT_HOST ?= 0

CFLAGS += \
  -D${MCU_VARIANT}
