if (NOT DEFINED CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER "iccarm")
endif()

if (NOT DEFINED CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER "iccarm")
endif()

if (NOT DEFINED CMAKE_ASM_COMPILER)
  set(CMAKE_ASM_COMPILER "iasmarm")
endif()

set(CMAKE_SIZE "size" CACHE FILEPATH "")
set(CMAKE_OBJCOPY "ielftool" CACHE FILEPATH "")
set(CMAKE_OBJDUMP "iefdumparm" CACHE FILEPATH "")

include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)
