::del *.zip /s
::del *.rar /s
del *.xml  /s
del *.crun  /s
del *.cspy.bat  /s
del *.dni  /s
del *.jlink /s
del *.scvd /s
del JLinkSettings.ini /s

del *.bak /s
del *.ddk /s
del *.edk /s
del *.lst /s
del *.lnp /s
del *.mpf /s
del *.mpj /s
del *.obj /s
del *.omf /s
::del *.opt /s  ::不允许删除JLINK的设置
del *.orig /s
del *.plg /s
del *.rpt /s
del *.tmp /s
del *.__i /s
del *.crf /s
del *.o /s
del *.d /s
del *.axf /s
del *.tra /s
del *.dep /s           
del JLinkLog.txt /s

del *.iex /s
del *.htm /s
del *.sct /s
del *.map /s
del *.hex /s
del *.uvoptx /s
del *.uvguix /s
del *.pbi /s
del *.pbi.cout /s
del *.out /s
del *.cout /s
del *.browse /s
del *.pbd /s
del *.TMP /s
del *.uvguix.* /s
del *.uvmpw.uvgui.* /s
del *.scc /s
del *.sim /s
del *.i /s
del *.pbi.xcl /s
del *.pbd.linf /s
del *.wsdt /s
del *.dbgdt /s
del *.wspos /s
del *.Debug.general.xcl /s
del *.Debug.driver.xcl /s
del *.pbw /s

del *.ewd /s
del *.ewt /s
del *.xcl /s
del *.dnx /s
del *.pbi /s
del *.Debug.cspy.ps1 /s
del build.ninja /s
del .ninja_deps /s
del .ninja_log /s
exit
