#ifndef NRFX_CONFIG_H__
#define NRFX_CONFIG_H__

#define NRFX_POWER_ENABLED              1
#define NRFX_POWER_CONFIG_IRQ_PRIORITY  7

#define NRFX_UARTE_ENABLED   1
#define NRFX_UARTE0_ENABLED  1

#endif // NRFX_CONFIG_H__
