#!/usr/bin/env python3
"""Regenerate the generated reference docs: docs/reference/dependencies.rst
(get_deps.py's table, also its --gen-doc), boards.rst from the metadata blocks in
hw/bsp/*/family.c and */boards/*/board.h, and hil_boards.md from the HIL
rosters. Boards and families without a metadata block are listed on stderr;
they are absent from boards.rst, not an error."""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / 'tools'))
from get_deps import gen_doc as gen_deps_doc, rst_table  # noqa: E402

HEADER = '<!-- Generated by .claude/skills/build-doc/scripts/gen_doc.py - do not edit. -->'


def metadata(path):
    """key: value pairs of the /* metadata: ... */ block, {} when the file or block is missing."""
    if not path.exists():
        return {}
    m = re.search(r'/\*\s*metadata:(.*?)\*/', path.read_text(), re.DOTALL)
    if not m:
        return {}
    return {k: v.strip() for k, v in re.findall(r'^[ \t]*(\w+):[ \t]*(.+)$', m.group(1), re.MULTILINE)}


def boards(bsp):
    """{manufacturer: {board: [name, family, url, note]}} plus the paths skipped for lack of metadata."""
    vendors, skipped = {}, []
    for family_dir in sorted(p for p in bsp.iterdir() if p.is_dir()):
        family_c = family_dir / 'family.c'
        if not family_c.exists():
            family_c = family_dir / 'boards' / 'family.c'
        f_meta = metadata(family_c)
        if not f_meta:
            skipped.append(family_dir)
            continue
        manufacturer = f_meta.get('manufacturer', '')
        for board_dir in sorted(p for p in (family_dir / 'boards').iterdir() if p.is_dir()):
            b_meta = metadata(board_dir / 'board.h')
            if not b_meta:
                skipped.append(board_dir)
                continue
            # setdefault here, not before the loop: a family whose boards are all
            # undocumented must not leave an empty vendor section behind.
            vendors.setdefault(manufacturer, {})[board_dir.name] = [
                b_meta.get('name', ''), family_dir.name, b_meta.get('url', ''), b_meta.get('note', '')]
    return vendors, skipped


def boards_rst(vendors):
    out = ['''\
****************
Supported Boards
****************

The board support code is only used for self-contained examples and testing. It is not used when TinyUSB is part of a larger project.
It is responsible for getting the MCU started and the USB peripheral clocked with minimal of on-board devices

-  One LED : for status
-  One Button : to get input from user
-  One UART : needed for logging with LOGGER=uart, maybe required for host/dual examples

Following boards are supported''']
    for vendor, entries in sorted(vendors.items()):
        rows = [[board, *entry] for board, entry in entries.items()]
        out.append(f'\n\n{vendor}\n{"-" * len(vendor)}\n\n'
                   + rst_table(['Board', 'Name', 'Family', 'URL', 'Note'], rows))
    return ''.join(out) + '\n'


def md_table(headers, rows):
    """GitHub-flavoured table, cells stripped, header at least two wider than its text."""
    rows = [[c.strip() for c in r] for r in rows]
    widths = [max([len(h) + 2] + [len(r[i]) for r in rows]) for i, h in enumerate(headers)]
    line = lambda cells: '| ' + ' | '.join(c.ljust(w) for c, w in zip(cells, widths)) + ' |'
    rule = '|' + '|'.join('-' * (w + 2) for w in widths) + '|'
    return '\n'.join([line(headers), rule, *(line(r) for r in rows)])


def hil_cell(text):
    """A '|' in free-form roster text would silently split the markdown row."""
    return ' '.join((text or '').split()).replace('|', '\\|')


def hil_rows(entries):
    rows = []
    for b in entries:
        tests = b.get('tests', {})
        if 'only' in tests:
            roles = sorted({t.split('/')[0] for t in tests['only']})
        else:
            roles = [r for r in ('device', 'host', 'dual') if tests.get(r)]
        rows.append([
            b['name'],
            ', '.join(roles),
            b.get('flasher', {}).get('name', ''),
            hil_cell(', '.join(v['name'] for v in b.get('variant') or [])),
            hil_cell(b.get('note') or tests.get('note')),
        ])
    return rows


def hil_md(root):
    out = [HEADER, '']
    for title, src in (('ci rig', 'test/hil/tinyusb.json'), ('hfp rig', 'test/hil/hfp.json')):
        entries = json.loads((root / src).read_text()).get('boards', [])
        if not entries:
            continue
        out += [f'### {title}', '', f'{len(entries)} boards, from `{src}`.', '',
                md_table(['Board', 'Roles', 'Flasher', 'Variants', 'Note'], hil_rows(entries)), '']
    return '\n'.join(out)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--root', type=Path, default=ROOT, help='repository to read and write (tests)')
    args = p.parse_args()
    root = args.root.resolve()

    gen_deps_doc(root / 'docs/reference/dependencies.rst')
    print(f'wrote {root / "docs/reference/dependencies.rst"}')
    vendors, skipped = boards(root / 'hw' / 'bsp')
    (root / 'docs/reference/boards.rst').write_text(boards_rst(vendors))
    print(f'wrote {root / "docs/reference/boards.rst"}')
    (root / 'docs/reference/hil_boards.md').write_text(hil_md(root))
    print(f'wrote {root / "docs/reference/hil_boards.md"}')
    if skipped:
        print('no metadata block, left out of boards.rst:', file=sys.stderr)
        for path in skipped:
            print(f'  {path.relative_to(root)}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
