/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief mclk direction control: MCLK is in the output direction. */
#define MCLKPINDIR_MCLKPINDIR_OUTPUT_DIRECTION 0x01u

/*! @name GPIO_5 (coord L7), J1[7]/MCLK
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_MCLKOUT_PERIPHERAL CLKCTL1                 /*!<@brief Peripheral name */
#define BOARD_INITPINS_MCLKOUT_SIGNAL MCLK                        /*!<@brief Signal name */
#define BOARD_INITPINS_MCLKOUT_GPIO_PIN 5U                        /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MCLKOUT_PORT 0U                            /*!<@brief PORT number */
#define BOARD_INITPINS_MCLKOUT_PIN 5U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_MCLKOUT_PIN_MASK (1U << 5U)                /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name GPIO_11 (coord M2), J1[6]/WAKEUP_BTN
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_WAKEUP_BTN_PERIPHERAL GPIO          /*!<@brief Peripheral name */
#define BOARD_INITPINS_WAKEUP_BTN_SIGNAL PIO0              /*!<@brief Signal name */
#define BOARD_INITPINS_WAKEUP_BTN_CHANNEL 11               /*!<@brief Signal channel */
#define BOARD_INITPINS_WAKEUP_BTN_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_WAKEUP_BTN_GPIO_PIN 11U             /*!<@brief GPIO pin number */
#define BOARD_INITPINS_WAKEUP_BTN_PORT 0U                  /*!<@brief PORT number */
#define BOARD_INITPINS_WAKEUP_BTN_PIN 11U                  /*!<@brief PORT pin number */
#define BOARD_INITPINS_WAKEUP_BTN_PIN_MASK (1U << 11U)     /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i] Mask for item 13. */
#define MCI_IO_MUX_GPIO_GRP0_SEL_13_MASK 0x2000u
/*!
 * @brief pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i] Mask for item 14. */
#define MCI_IO_MUX_GPIO_GRP0_SEL_14_MASK 0x4000u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[21:0] Mask for item 13. */
#define SOCCIU_MCI_IOMUX_EN0_EN_21_0_13_MASK 0x2000u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[21:0] Mask for item 14. */
#define SOCCIU_MCI_IOMUX_EN0_EN_21_0_14_MASK 0x4000u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void); /* Function assigned for the Cortex-M33 */

/*! @name GPIO_0 (coord M1), J1[14]/LED_BLUE
  @{ */
/* Routed pin properties */
#define BOARD_INITLEDPINS_LED_BLUE_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITLEDPINS_LED_BLUE_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITLEDPINS_LED_BLUE_CHANNEL 0                          /*!<@brief Signal channel */
#define BOARD_INITLEDPINS_LED_BLUE_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_LED_BLUE_INIT_GPIO_VALUE 1U                 /*!<@brief GPIO output initial state */
#define BOARD_INITLEDPINS_LED_BLUE_GPIO_PIN 0U                        /*!<@brief GPIO pin number */
#define BOARD_INITLEDPINS_LED_BLUE_PORT 0U                            /*!<@brief PORT number */
#define BOARD_INITLEDPINS_LED_BLUE_PIN 0U                             /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_BLUE_PIN_MASK (1U << 0U)                /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name GPIO_1 (coord N2), J5[1]/LED_RED
  @{ */
/* Routed pin properties */
#define BOARD_INITLEDPINS_LED_RED_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITLEDPINS_LED_RED_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITLEDPINS_LED_RED_CHANNEL 1                          /*!<@brief Signal channel */
#define BOARD_INITLEDPINS_LED_RED_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_LED_RED_INIT_GPIO_VALUE 1U                 /*!<@brief GPIO output initial state */
#define BOARD_INITLEDPINS_LED_RED_GPIO_PIN 1U                        /*!<@brief GPIO pin number */
#define BOARD_INITLEDPINS_LED_RED_PORT 0U                            /*!<@brief PORT number */
#define BOARD_INITLEDPINS_LED_RED_PIN 1U                             /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_RED_PIN_MASK (1U << 1U)                /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name GPIO_12 (coord N8), LED_GREEN
  @{ */
/* Routed pin properties */
#define BOARD_INITLEDPINS_LED_GREEN_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITLEDPINS_LED_GREEN_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITLEDPINS_LED_GREEN_CHANNEL 12                         /*!<@brief Signal channel */
#define BOARD_INITLEDPINS_LED_GREEN_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_LED_GREEN_INIT_GPIO_VALUE 1U                 /*!<@brief GPIO output initial state */
#define BOARD_INITLEDPINS_LED_GREEN_GPIO_PIN 12U                       /*!<@brief GPIO pin number */
#define BOARD_INITLEDPINS_LED_GREEN_PORT 0U                            /*!<@brief PORT number */
#define BOARD_INITLEDPINS_LED_GREEN_PIN 12U                            /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_GREEN_PIN_MASK (1U << 12U)               /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
