MCU_VARIANT = HPM6750xVMx
JLINK_DEVICE = ${MCU_VARIANT}

JLINK_IF = jtag

HPM_SOC = $(SDK_DIR)/soc/HPM6700/HPM6750
HPM_IP_REGS = $(SDK_DIR)/soc/HPM6700/ip

BOARD_FLASH_SIZE = 16M
BOARD_STACK_SIZE = 16K
BOARD_HEAP_SIZE = 16K

BOARD_TUD_RHPORT = 0
BOARD_TUH_RHPORT = 1

HPM_PLLCTL_DRV_FILE = hpm_pllctl_drv.c
