
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart2_pins(void);
void init_uart13_pins(void);
void init_puart_pins(void);
void init_uart13_pins_as_gpio(void);
void init_lcd0_pins(void);
void init_cap_pins(void);
void init_i2c0_pins_as_gpio(void);
void init_i2c0_pins(void);
void init_femc_pins(void);
void init_gpio_pins_with_pull_up(void);
void init_gpio_pins_using_gpio0(void);
void init_spi2_pins(void);
void init_spi2_pins_with_gpio_as_cs(void);
void init_gptmr3_pins(void);
void init_gptmr4_pins(void);
void init_gptmr5_pins(void);
void init_hall_trgm_pins(void);
void init_qei_trgm_pins(void);
void init_i2s0_pins(void);
void init_dao_pins(void);
void init_pdm_pins(void);
void init_vad_pins(void);
void init_cam_pins(void);
void init_butn_pins(void);
void init_acmp_pins(void);
void init_enet0_pins(void);
void init_enet1_pins(void);
void init_pwm2_pins(void);
void init_pwm3_pins(void);
void init_adc12_pins(void);
void init_adc16_pins(void);
void init_adc_bldc_pins(void);
void init_usb0_pins(void);
void init_usb1_pins(void);
void init_can0_pins(void);
void init_mcan0_transceiver_phy_pin(void);
void init_sdxc1_cmd_pin_enable_1v8_enable_opendrain(void);
void init_sdxc1_cmd_pin_enable_1v8_disable_opendrain(void);
void init_sdxc1_cmd_pin_disable_1v8_enable_opendrain(void);
void init_sdxc1_cmd_pin_disable_1v8_disable_opendrain(void);
void init_sdxc1_cd_pin(void);
void init_sdxc1_clk_data_pins_enable_1v8(void);
void init_sdxc1_clk_data_pins_disable_1v8(void);
void init_sdxc1_clk_data_pins_width4_enable_1v8(void);
void init_sdxc1_clk_data_pins_width4_disable_1v8(void);
void init_sdxc1_pwr_pin(void);
void init_clk_obs_pins(void);
void init_rgb_pwm_pins(void);
void init_led_pins_as_gpio(void);
void init_enet_pps_pins(void);
void init_enet_pps_capture_pins(void);
void init_tamper_pins(void);
void init_uart_break_signal_pin(void);
void init_gptmr3_channel_pin_as_output(void);
void init_gptmr4_channel_pin_as_capture(void);
void init_gptmr5_channel2_pin_as_output(void);
void init_gptmr5_channel3_pin_as_output(void);
void init_clk_ref_pin(void);
void init_brownout_indicate_pin(void);
void board_init_i2c_eeprom_pin(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
