name: Setup Toolchain

inputs:
  toolchain:
    required: true
    type: string
  toolchain_url:
    required: false
    type: string

outputs:
  build_option:
    description: 'Build option for the toolchain e.g --toolchain clang'
    value: ${{ steps.set-toolchain-option.outputs.build_option }}

runs:
  using: "composite"
  steps:
    - name: Install ARM GCC
      if: inputs.toolchain == 'arm-gcc'
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.3.Rel1'

    - name: Pull ESP-IDF docker
      if: inputs.toolchain == 'esp-idf'
      run: docker pull espressif/idf:${{ inputs.toolchain_url }}
      shell: bash

    - name: Download Toolchain
      if: >-
        inputs.toolchain != 'arm-gcc' &&
        inputs.toolchain != 'esp-idf'
      uses: ./.github/actions/setup_toolchain/download
      with:
        toolchain_url: ${{ inputs.toolchain_url }}

    - name: Set toolchain option
      id: set-toolchain-option
      run: |
          BUILD_OPTION=""
          if [[ "${{ inputs.toolchain }}" == *"clang"* ]]; then
            BUILD_OPTION="--toolchain clang"
          fi
          echo "build_option=$BUILD_OPTION"
          echo "build_option=$BUILD_OPTION" >> $GITHUB_OUTPUT
      shell: bash
