name: Setup Toolchain

inputs:
  toolchain:
    required: true
    type: string
  toolchain_url:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Install ARM GCC
      if: inputs.toolchain == 'arm-gcc'
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.3.Rel1'

    - name: Pull ESP-IDF docker
      if: inputs.toolchain == 'esp-idf'
      run: docker pull espressif/idf:latest
      shell: bash

    - name: Download Toolchain
      if: >-
        inputs.toolchain != 'arm-gcc' &&
        inputs.toolchain != 'esp-idf'
      uses: ./.github/actions/setup_toolchain/download
      with:
        toolchain_url: ${{ inputs.toolchain_url }}
