name: Setup ESP-IDF Toolchain

inputs:
  toolchain:
    description: 'Toolchain name'
    required: true
  toolchain_url:
    description: 'Toolchain URL or version'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "DOCKER_IMAGE=~/cache/${{ inputs.toolchain }}/docker_image.tar" >> $GITHUB_ENV
      shell: bash

    - name: Cache Docker Image
      uses: actions/cache@v4
      id: cache-toolchain-espressif
      with:
        path: $DOCKER_IMAGE
        key: ${{ runner.os }}-${{ inputs.toolchain }}-${{ inputs.toolchain_url }}

    - name: Pull and Save Docker Image
      if: steps.cache-toolchain-espressif.outputs.cache-hit != 'true'
      run: |
        docker pull espressif/idf:${{ inputs.toolchain_url }}
        mkdir -p ~/cache/${{ inputs.toolchain }}
        docker save espressif/idf:${{ inputs.toolchain_url }} > $DOCKER_IMAGE
      shell: bash

    - name: Load Docker Image
      if: steps.cache-toolchain-espressif.outputs.cache-hit == 'true'
      run: |
        docker load < $DOCKER_IMAGE
      shell: bash
