name: Setup ESP-IDF Toolchain

inputs:
  toolchain:
    description: 'Toolchain name'
    required: true
  toolchain_url:
    description: 'Toolchain URL or version'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "DOCKER_IMAGE=$HOME/cache/${{ inputs.toolchain }}/docker_image.tar" >> $GITHUB_ENV
      shell: bash

    - name: Cache Docker Image
      uses: actions/cache@v4
      id: cache-toolchain-espressif
      with:
        path: $DOCKER_IMAGE
        key: ${{ runner.os }}-${{ inputs.toolchain }}-${{ inputs.toolchain_url }}

    - name: Load Docker Image
      if: steps.cache-toolchain-espressif.outputs.cache-hit == 'true'
      run: |
        tree ~/cache
        docker load --input $DOCKER_IMAGE
      shell: bash

    - name: Pull and Save Docker Image
      if: steps.cache-toolchain-espressif.outputs.cache-hit != 'true'
      run: |
        docker pull espressif/idf:${{ inputs.toolchain_url }}
        mkdir -p ~/cache/${{ inputs.toolchain }}
        tree ~/cache
        docker save -o $DOCKER_IMAGE espressif/idf:${{ inputs.toolchain_url }} || exit 1
        tree ~/cache
      shell: bash
