// SPDX-License-Identifier: MIT
#ifndef TUSB_CONFIG_H_
#define TUSB_CONFIG_H_
#define CFG_TUSB_MCU OPT_MCU_NONE
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUSB_DEBUG 0
#define CFG_TUH_ENABLED 1
#define CFG_TUH_MAX_SPEED OPT_MODE_HIGH_SPEED
#define CFG_TUH_DEVICE_MAX 4
#define CFG_TUH_HUB 1
#define TUP_USBIP_EHCI
#define TUP_USBIP_CHIPIDEA_HS
#endif
