name: Build family

on:
  workflow_call:
    inputs:
      family:
        required: true
        type: string
      toolchain_url:
        required: true
        type: string

jobs:
  board:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        family: ${{ inputs.family }}
    steps:
      - name: Checkout TinyUSB
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Toolchain
        uses: ./.github/actions/setup_toolchain
        with:
          toolchain_url: ${{ inputs.toolchain_url }}

      - name: Prepare to build
        uses: ./.github/actions/prepare_build
        with:
          family: ${{ matrix.family }}

      - name: Checkout pico-sdk for rp2040
        if: contains(matrix.family, 'rp2040')
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: pico-sdk

      - name: Get Dependencies
        run: |
          sudo apt install -y ninja-build
          python3 tools/get_deps.py ${{ matrix.family }}
          echo >> $GITHUB_ENV "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk"

      - name: Build
        run: python tools/build_cmake.py ${{ matrix.family }}
